DevopsConfig:
  Github:
    Repository: "Meheer17/TS"
    Path: "/path/to/your/file"
    Environment:
      Production:
        Branch: "main"
      Staging:
        Branch: "staging"
      Development:
        Branch: "development"
      Test:
        Branch: "test"
      QA:
        Branch: "qa"
      PreProduction:
        Branch: "pre-production"

  Cloud:
    GCP:
      ProjectID: "arty-facets"
      Zone: "ap-south1-a"
      Region: "ap-south1"
      Compute-Type: "e2-micro"
      Name: "Mahi"

  Tools:
    Docker: true
    Kubernetes: true
    Instances: true
    Monitoring: true
    Logging: true
    Nginx: true
    Prometheus: true
    Grafana: true
