DevopsConfig:
  Github:
    Repository: "Meheer17/TS"
    Path: "/path/to/your/file"
    Environment:
      Production:
        Branch: "main"
      Staging:
        Branch: "staging"
      Development:
        Branch: "development"
      Test:
        Branch: "test"
      QA:
        Branch: "qa"
      PreProduction:
        Branch: "pre-production"

  Cloud:
    GCP:
      Zone: "asia-south1-a"
      Region: "asia-south1"
      Compute-Type: "e2-micro"
      Name: "mahi"
      SSH-Private: "./mahiasd"
      SSH-PUBLIC: "./mahiasd.pub"
  Tools:
    Docker: true
    Kubernetes: true
    Instances: true
    Monitoring: true
    Logging: true
    Nginx: true
    Prometheus: true
    Grafana: true

  Explanation:
    Explanation: "This is a Nextjs website and dockerized application"
